import { ScrollViewStyleReset } from 'expo-router/html';
import React from 'react';

/**
 * HTML shell for the Expo web build.
 *
 * Preloads the three Plus Jakarta Sans weights + MaterialIcons so they begin
 * downloading before the JS bundle executes, and declares @font-face rules
 * with font-display:swap so Chrome never needs to apply its slow-network font
 * loading intervention (which generates console warnings and flashes fallback
 * text).
 *
 * The filenames contain a content hash generated by Expo's asset pipeline.
 * Update these paths if you upgrade @expo-google-fonts/plus-jakarta-sans or
 * @expo/vector-icons and a new build produces a different hash.
 */

const FONT_400 =
  '/assets/node_modules/@expo-google-fonts/plus-jakarta-sans/400Regular/PlusJakartaSans_400Regular.dd3a1370a03dc0f2d7d093bd0ffe7c0b.ttf';
const FONT_600 =
  '/assets/node_modules/@expo-google-fonts/plus-jakarta-sans/600SemiBold/PlusJakartaSans_600SemiBold.73de6fb49299ccb6478575127008c120.ttf';
const FONT_700 =
  '/assets/node_modules/@expo-google-fonts/plus-jakarta-sans/700Bold/PlusJakartaSans_700Bold.bac8ecad2d6da4aa6b4200699a80a9dd.ttf';
const FONT_ICONS =
  '/assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/MaterialIcons.4e85bc9ebe07e0340c9c4fc2f6c38908.ttf';

const FONT_FACE_CSS = `
@font-face {
  font-family: 'PlusJakartaSans_400Regular';
  src: url('${FONT_400}') format('truetype');
  font-weight: 400;
  font-style: normal;
  font-display: swap;
}
@font-face {
  font-family: 'PlusJakartaSans_600SemiBold';
  src: url('${FONT_600}') format('truetype');
  font-weight: 600;
  font-style: normal;
  font-display: swap;
}
@font-face {
  font-family: 'PlusJakartaSans_700Bold';
  src: url('${FONT_700}') format('truetype');
  font-weight: 700;
  font-style: normal;
  font-display: swap;
}
@font-face {
  font-family: 'MaterialIcons';
  src: url('${FONT_ICONS}') format('truetype');
  font-weight: 400;
  font-style: normal;
  font-display: block;
}
`;

export default function Root({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        {/* Preload critical fonts — tells the browser to fetch these before JS runs */}
        <link rel="preload" as="font" type="font/ttf" crossOrigin="anonymous" href={FONT_700} />
        <link rel="preload" as="font" type="font/ttf" crossOrigin="anonymous" href={FONT_600} />
        <link rel="preload" as="font" type="font/ttf" crossOrigin="anonymous" href={FONT_400} />
        <link rel="preload" as="font" type="font/ttf" crossOrigin="anonymous" href={FONT_ICONS} />

        {/* font-display:swap — browser renders text immediately with fallback font,
            then swaps to custom font once loaded. Eliminates Chrome's intervention. */}
        {/* eslint-disable-next-line react/no-danger */}
        <style dangerouslySetInnerHTML={{ __html: FONT_FACE_CSS }} />

        <ScrollViewStyleReset />
      </head>
      <body>{children}</body>
    </html>
  );
}
