FROM node:20-alpine
WORKDIR /app

ENV EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile || yarn install

COPY . .

EXPOSE 19006 19000 19001
CMD ["yarn", "web", "--", "--host", "lan", "--port", "19006"]
