import type { MobileAppConfig } from './appConfig.schema';

export const DEFAULT_MOBILE_APP_CONFIG: MobileAppConfig = {
  version: 6,
  privacy: {
    contactEmail: 'privacy@claudygod.org',
    deleteConfirmPhrase: 'I CONFIRM',
    principles: [
      'We do not sell personal data.',
      'Security controls are available from inside the app.',
      'Privacy requests are processed by a human support team.',
      'Activity-based personalization can be reset by the user.',
    ],
  },
  help: {
    supportCenterUrl: 'https://claudygod.org',
    contact: [
      {
        id: 'website',
        icon: 'public',
        title: 'Ministry website',
        desc: 'Open the ClaudyGod website',
        actionUrl: 'https://claudygod.org',
      },
      {
        id: 'email',
        icon: 'email',
        title: 'Email support',
        desc: 'support@claudygod.org',
        actionUrl: 'mailto:support@claudygod.org',
      },
      {
        id: 'whatsapp',
        icon: 'forum',
        title: 'WhatsApp support',
        desc: 'Message the ministry support desk',
        actionUrl: 'https://wa.me/18002528394',
      },
      {
        id: 'phone',
        icon: 'phone',
        title: 'Call support',
        desc: '+1 (800) 252-8394',
        actionUrl: 'tel:+18002528394',
      },
    ],
    faqs: [
      {
        id: 'buffering-tv',
        q: 'Playback buffering on TV?',
        a: 'Use Ethernet or 5GHz Wi-Fi and keep playback quality on Adaptive mode.',
      },
      {
        id: 'downloads-missing',
        q: 'Downloads not showing?',
        a: 'Open Library → Downloads and refresh. Check if storage permission is allowed.',
      },
      {
        id: 'recommendations-wrong',
        q: 'Wrong recommendations?',
        a: 'Clear watch and listen history in Privacy settings to reset suggestions.',
      },
      {
        id: 'report-content',
        q: 'How do I report content?',
        a: 'Open track menu and tap Report, or send the media link to support email.',
      },
    ],
  },
  about: {
    heroStats: [
      { label: 'Platforms', value: 'Mobile + Web' },
      { label: 'Support desk', value: 'Human-led' },
      { label: 'Content flow', value: 'Daily' },
    ],
    featureChips: [
      { icon: 'library-music', label: 'Worship releases' },
      { icon: 'smart-display', label: 'Video replays' },
      { icon: 'menu-book', label: 'Daily word' },
      { icon: 'cast', label: 'TV + web ready' },
      { icon: 'lock', label: 'Secure access' },
      { icon: 'support-agent', label: 'Support desk' },
    ],
    team: [
      { name: 'Claudy God', role: 'Founder & Lead Artist', desc: 'Vision, music direction, and weekly drops.' },
      { name: 'Product Crew', role: 'Experience', desc: 'Design systems, research, and accessibility.' },
      { name: 'Engineering', role: 'Platform', desc: 'Streaming quality, playback reliability, and APIs.' },
    ],
    social: [
      { icon: 'public', label: 'Website', url: 'https://claudygod.org' },
      { icon: 'smart-display', label: 'YouTube', url: 'https://www.youtube.com/@ClaudyGODMinistries' },
      { icon: 'forum', label: 'WhatsApp', url: 'https://wa.me/18002528394' },
      { icon: 'alternate-email', label: 'Support', url: 'mailto:support@claudygod.org' },
    ],
    versionLabel: 'Version 1.0.0',
  },
  donate: {
    currency: 'USD',
    quickAmounts: ['$5', '$10', '$25', '$50', '$100'],
    methods: [
      {
        id: 'card',
        icon: 'credit-card',
        label: 'Card / Apple Pay / Google Pay',
        subtitle: 'Fast checkout with secure payment providers',
        badge: 'Recommended',
      },
      {
        id: 'bank',
        icon: 'account-balance',
        label: 'Bank transfer',
        subtitle: 'Manual transfer and reconciliation support',
      },
      {
        id: 'sponsor',
        icon: 'volunteer-activism',
        label: 'Sponsor a live session',
        subtitle: 'Fund one broadcast or a ministry campaign slot',
      },
    ],
    plans: [
      {
        id: 'supporter',
        name: 'Supporter',
        amount: '$10',
        period: 'monthly',
        note: 'Helps cover storage, bandwidth and publishing operations.',
        icon: 'favorite-border',
      },
      {
        id: 'partner',
        name: 'Partner',
        amount: '$25',
        period: 'monthly',
        note: 'Supports music drops, live streaming and content production.',
        featured: true,
        icon: 'auto-awesome',
      },
      {
        id: 'mission',
        name: 'Mission Gift',
        amount: '$100',
        period: 'once',
        note: 'One-time support for outreach campaigns and platform improvements.',
        icon: 'public',
      },
    ],
    impactBreakdown: [
      { label: 'Streaming & CDN', value: 42, icon: 'wifi-tethering' },
      { label: 'Production & Editing', value: 33, icon: 'movie-edit' },
      { label: 'Outreach & Events', value: 25, icon: 'groups' },
    ],
  },
  rate: {
    iosStoreUrl: 'https://apps.apple.com/app/idYOUR_APP_ID',
    androidStoreUrl: 'https://play.google.com/store/apps/details?id=com.claudygod.mobile',
    feedbackRoute: '/settingsPage/help',
  },
  layout: {
    homeSections: [
      {
        id: 'claudygod-music',
        title: 'ClaudyGod (Music)',
        subtitle: 'Official music releases and worship audio.',
        contentTypes: ['audio', 'playlist'],
        actionLabel: 'Listen',
        destinationTab: 'player',
        maxItems: 8,
      },
      {
        id: 'claudygod-nuggets-of-truth',
        title: 'ClaudyGod (Nuggets of Truth)',
        subtitle: 'Short teachings, reflections, and devotionals.',
        contentTypes: ['announcement', 'audio', 'video'],
        actionLabel: 'Open',
        destinationTab: 'home',
        maxItems: 8,
      },
      {
        id: 'claudygod-worship-hour',
        title: 'ClaudyGod Worship Hour',
        subtitle: 'Worship sessions, replays, and live moments.',
        contentTypes: ['audio', 'video', 'live'],
        actionLabel: 'Watch',
        destinationTab: 'videos',
        maxItems: 8,
      },
      {
        id: 'claudygod-teens',
        title: 'ClaudyGod Teens',
        subtitle: 'Youth-focused worship and messages.',
        contentTypes: ['video', 'audio'],
        actionLabel: 'Open',
        destinationTab: 'videos',
        maxItems: 8,
      },
      {
        id: 'claudygod-kids',
        title: 'ClaudyGod Kids',
        subtitle: 'Kids-friendly worship and learning.',
        contentTypes: ['video', 'audio'],
        actionLabel: 'Open',
        destinationTab: 'videos',
        maxItems: 8,
      },
      {
        id: 'claudygod-speaks',
        title: 'ClaudyGod Speaks',
        subtitle: 'Messages, teachings, and ministry updates.',
        contentTypes: ['announcement', 'video', 'live'],
        actionLabel: 'Watch',
        destinationTab: 'videos',
        maxItems: 8,
      },
    ],
    videoSections: [
      {
        id: 'claudygod-worship-hour',
        title: 'ClaudyGod Worship Hour',
        subtitle: 'Worship sessions and live replays.',
        contentTypes: ['video', 'live'],
        actionLabel: 'Watch',
        destinationTab: 'videos',
        maxItems: 10,
      },
      {
        id: 'claudygod-teens',
        title: 'ClaudyGod Teens',
        subtitle: 'Youth-focused worship and messages.',
        contentTypes: ['video'],
        actionLabel: 'Open',
        destinationTab: 'videos',
        maxItems: 10,
      },
      {
        id: 'claudygod-kids',
        title: 'ClaudyGod Kids',
        subtitle: 'Kids-friendly worship and learning.',
        contentTypes: ['video'],
        actionLabel: 'Open',
        destinationTab: 'videos',
        maxItems: 10,
      },
      {
        id: 'claudygod-speaks',
        title: 'ClaudyGod Speaks',
        subtitle: 'Messages, teachings, and ministry updates.',
        contentTypes: ['video', 'announcement', 'live'],
        actionLabel: 'Watch',
        destinationTab: 'videos',
        maxItems: 10,
      },
    ],
    playerSections: [
      {
        id: 'claudygod-music',
        title: 'ClaudyGod (Music)',
        subtitle: 'Official music releases and worship audio.',
        contentTypes: ['audio', 'playlist'],
        actionLabel: 'Listen',
        destinationTab: 'player',
        maxItems: 12,
      },
      {
        id: 'claudygod-nuggets-of-truth',
        title: 'ClaudyGod (Nuggets of Truth)',
        subtitle: 'Short teachings and devotionals for listening.',
        contentTypes: ['audio', 'announcement'],
        actionLabel: 'Open',
        destinationTab: 'player',
        maxItems: 10,
      },
      {
        id: 'claudygod-worship-hour',
        title: 'ClaudyGod Worship Hour',
        subtitle: 'Long-form worship and replays.',
        contentTypes: ['audio', 'playlist'],
        actionLabel: 'Listen',
        destinationTab: 'player',
        maxItems: 10,
      },
    ],
    librarySections: [
      {
        id: 'claudygod-music',
        title: 'ClaudyGod (Music)',
        subtitle: 'Saved worship audio and playlists.',
        contentTypes: ['audio', 'playlist'],
        actionLabel: 'Play',
        destinationTab: 'player',
        maxItems: 10,
      },
      {
        id: 'claudygod-speaks',
        title: 'ClaudyGod Speaks',
        subtitle: 'Saved messages and video replays.',
        contentTypes: ['video', 'live'],
        actionLabel: 'Watch',
        destinationTab: 'videos',
        maxItems: 10,
      },
      {
        id: 'claudygod-kids',
        title: 'ClaudyGod Kids',
        subtitle: 'Saved kids content.',
        contentTypes: ['video', 'audio'],
        actionLabel: 'Open',
        destinationTab: 'videos',
        maxItems: 8,
      },
    ],
  },
  navigation: {
    tabs: [
      { id: 'home', label: 'Home', icon: 'home-filled' },
      { id: 'player', label: 'Music', icon: 'graphic-eq' },
      { id: 'videos', label: 'Videos', icon: 'smart-display' },
      { id: 'live', label: 'Live', icon: 'live-tv' },
      { id: 'library', label: 'Library', icon: 'library-music' },
    ],
  },
  discovery: {
    categories: ['All', 'audio', 'video', 'playlist', 'live', 'announcement'],
    shortcuts: [
      {
        id: 'worship',
        icon: 'graphic-eq',
        label: 'Trending worship',
        query: 'worship',
        category: 'audio',
      },
      {
        id: 'live',
        icon: 'live-tv',
        label: 'Live now',
        query: 'live',
        category: 'live',
      },
      {
        id: 'message',
        icon: 'menu-book',
        label: 'Message audio',
        query: 'message',
        category: 'announcement',
      },
    ],
  },
  settingsHub: {
    sections: [
      {
        id: 'account',
        title: 'Account',
        items: [
          {
            id: 'profile',
            icon: 'person-outline',
            label: 'Profile',
            hint: 'Name, email, and account details',
            destination: 'profile',
          },
          {
            id: 'library',
            icon: 'library-music',
            label: 'Your Library',
            hint: 'Saved listening and playlists',
            destination: 'tabs.library',
          },
          {
            id: 'privacy',
            icon: 'shield',
            label: 'Privacy',
            hint: 'Permissions and account controls',
            destination: 'settings.privacy',
          },
        ],
      },
      {
        id: 'discover',
        title: 'Discover',
        items: [
        {
          id: 'live',
          icon: 'live-tv',
          label: 'Live & Replays',
          hint: 'Current broadcasts, upcoming sessions, and recent replays',
          destination: 'tabs.live',
        },
        {
          id: 'videos',
          icon: 'ondemand-video',
          label: 'Video Hub',
          hint: 'Featured watchlists, live clips, and message replays',
          destination: 'tabs.videos',
        },
          {
            id: 'donate',
            icon: 'volunteer-activism',
            label: 'Support the Ministry',
            hint: 'Give and support the mission',
            destination: 'settings.donate',
          },
        ],
      },
      {
        id: 'support',
        title: 'Support',
        items: [
          {
            id: 'help',
            icon: 'help-outline',
            label: 'Help',
            hint: 'FAQs and support options',
            destination: 'settings.help',
          },
          {
            id: 'about',
            icon: 'info-outline',
            label: 'About ClaudyGod',
            hint: 'Learn about the ministry and the platform',
            destination: 'settings.about',
          },
          {
            id: 'rate',
            icon: 'rate-review',
            label: 'Rate App',
            hint: 'Share feedback about the experience',
            destination: 'settings.rate',
          },
        ],
      },
    ],
  },
  monetization: {
    adsEnabled: true,
    disclosureLabel: 'Sponsored',
    placements: [
      {
        id: 'landing-hero',
        title: 'Landing promotion',
        subtitle: 'Featured campaign slot for the public landing experience.',
        screen: 'landing',
        enabled: true,
        maxItems: 1,
      },
      {
        id: 'home-spotlight',
        title: 'Home spotlight',
        subtitle: 'Sponsored placement inside the signed-in home feed.',
        screen: 'home',
        enabled: true,
        maxItems: 1,
      },
      {
        id: 'video-spotlight',
        title: 'Video spotlight',
        subtitle: 'Campaigns targeted at the video screen.',
        screen: 'videos',
        enabled: true,
        maxItems: 1,
      },
      {
        id: 'music-spotlight',
        title: 'Music spotlight',
        subtitle: 'Campaigns targeted at listening flows and the player screen.',
        screen: 'player',
        enabled: true,
        maxItems: 1,
      },
    ],
  },
  intelligence: {
    assistantEnabled: true,
    adCopySuggestionsEnabled: true,
    providerLabel: 'Integrated AI',
    defaultTone: 'Confident, concise, ministry-safe',
  },
};
