import type { MobileAppConfig } from './appConfig.schema';

export const DEFAULT_MOBILE_APP_CONFIG: MobileAppConfig = {
  version: 5,
  privacy: {
    contactEmail: 'privacy@claudygod.org',
    deleteConfirmPhrase: 'I CONFIRM',
    principles: [
      'We do not sell personal data.',
      'Security controls are available from inside the app.',
      'Privacy requests are processed by a human support team.',
      'Activity-based personalization can be reset by the user.',
    ],
  },
  help: {
    supportCenterUrl: 'https://claudygod.org',
    contact: [
      {
        id: 'website',
        icon: 'public',
        title: 'Ministry website',
        desc: 'Open the ClaudyGod website',
        actionUrl: 'https://claudygod.org',
      },
      {
        id: 'email',
        icon: 'email',
        title: 'Email support',
        desc: 'support@claudygod.org',
        actionUrl: 'mailto:support@claudygod.org',
      },
      {
        id: 'whatsapp',
        icon: 'forum',
        title: 'WhatsApp support',
        desc: 'Message the ministry support desk',
        actionUrl: 'https://wa.me/18002528394',
      },
      {
        id: 'phone',
        icon: 'phone',
        title: 'Call support',
        desc: '+1 (800) 252-8394',
        actionUrl: 'tel:+18002528394',
      },
    ],
    faqs: [
      {
        id: 'buffering-tv',
        q: 'Playback buffering on TV?',
        a: 'Use Ethernet or 5GHz Wi-Fi and keep playback quality on Adaptive mode.',
      },
      {
        id: 'downloads-missing',
        q: 'Downloads not showing?',
        a: 'Open Library → Downloads and refresh. Check if storage permission is allowed.',
      },
      {
        id: 'recommendations-wrong',
        q: 'Wrong recommendations?',
        a: 'Clear watch and listen history in Privacy settings to reset suggestions.',
      },
      {
        id: 'report-content',
        q: 'How do I report content?',
        a: 'Open track menu and tap Report, or send the media link to support email.',
      },
    ],
  },
  about: {
    heroStats: [
      { label: 'Platforms', value: 'Mobile + Web' },
      { label: 'Support desk', value: 'Human-led' },
      { label: 'Content flow', value: 'Daily' },
    ],
    featureChips: [
      { icon: 'library-music', label: 'Worship releases' },
      { icon: 'smart-display', label: 'Video replays' },
      { icon: 'menu-book', label: 'Daily word' },
      { icon: 'cast', label: 'TV + web ready' },
      { icon: 'lock', label: 'Secure access' },
      { icon: 'support-agent', label: 'Support desk' },
    ],
    team: [
      { name: 'Claudy God', role: 'Founder & Lead Artist', desc: 'Vision, music direction, and weekly drops.' },
      { name: 'Product Crew', role: 'Experience', desc: 'Design systems, research, and accessibility.' },
      { name: 'Engineering', role: 'Platform', desc: 'Streaming quality, playback reliability, and APIs.' },
    ],
    social: [
      { icon: 'public', label: 'Website', url: 'https://claudygod.org' },
      { icon: 'smart-display', label: 'YouTube', url: 'https://www.youtube.com/@ClaudyGODMinistries' },
      { icon: 'forum', label: 'WhatsApp', url: 'https://wa.me/18002528394' },
      { icon: 'alternate-email', label: 'Support', url: 'mailto:support@claudygod.org' },
    ],
    versionLabel: 'Version 1.0.0',
  },
  donate: {
    currency: 'USD',
    quickAmounts: ['$5', '$10', '$25', '$50', '$100'],
    methods: [
      {
        id: 'card',
        icon: 'credit-card',
        label: 'Card / Apple Pay / Google Pay',
        subtitle: 'Fast checkout with secure payment providers',
        badge: 'Recommended',
      },
      {
        id: 'bank',
        icon: 'account-balance',
        label: 'Bank transfer',
        subtitle: 'Manual transfer and reconciliation support',
      },
      {
        id: 'sponsor',
        icon: 'volunteer-activism',
        label: 'Sponsor a live session',
        subtitle: 'Fund one broadcast or a ministry campaign slot',
      },
    ],
    plans: [
      {
        id: 'supporter',
        name: 'Supporter',
        amount: '$10',
        period: 'monthly',
        note: 'Helps cover storage, bandwidth and publishing operations.',
        icon: 'favorite-border',
      },
      {
        id: 'partner',
        name: 'Partner',
        amount: '$25',
        period: 'monthly',
        note: 'Supports music drops, live streaming and content production.',
        featured: true,
        icon: 'auto-awesome',
      },
      {
        id: 'mission',
        name: 'Mission Gift',
        amount: '$100',
        period: 'once',
        note: 'One-time support for outreach campaigns and platform improvements.',
        icon: 'public',
      },
    ],
    impactBreakdown: [
      { label: 'Streaming & CDN', value: 42, icon: 'wifi-tethering' },
      { label: 'Production & Editing', value: 33, icon: 'movie-edit' },
      { label: 'Outreach & Events', value: 25, icon: 'groups' },
    ],
  },
  rate: {
    iosStoreUrl: 'https://apps.apple.com/app/idYOUR_APP_ID',
    androidStoreUrl: 'https://play.google.com/store/apps/details?id=com.claudygod.mobile',
    feedbackRoute: '/settingsPage/help',
  },
  layout: {
    homeSections: [
      {
        id: 'claudygod-music',
        title: 'ClaudyGod Music',
        subtitle: 'Featured worship videos and music drops on the mobile dashboard.',
        contentTypes: ['video', 'live'],
        actionLabel: 'Watch',
        destinationTab: 'videos',
        maxItems: 8,
      },
      {
        id: 'claudygod-nuggets-of-truth',
        title: 'ClaudyGod Nuggets of Truth',
        subtitle: 'Daily truth, devotional snippets, and scripture-led moments.',
        contentTypes: ['announcement', 'video'],
        actionLabel: 'Open',
        destinationTab: 'home',
        maxItems: 8,
      },
      {
        id: 'claudygod-worship-hour',
        title: 'ClaudyGod Worship Hour',
        subtitle: 'Worship sets, replays, and atmosphere-building collections.',
        contentTypes: ['video', 'playlist', 'live'],
        actionLabel: 'Live',
        destinationTab: 'live',
        maxItems: 8,
      },
      {
        id: 'claudygod-messages',
        title: 'ClaudyGod Messages',
        subtitle: 'Teaching, message replays, and ministry updates.',
        contentTypes: ['announcement', 'video'],
        actionLabel: 'Browse',
        destinationTab: 'videos',
        maxItems: 8,
      },
      {
        id: 'claudygod-music-audio',
        title: 'ClaudyGod Music (Audio)',
        subtitle: 'Pure audio releases that should lead straight into the music player.',
        contentTypes: ['audio', 'playlist'],
        actionLabel: 'Listen',
        destinationTab: 'player',
        maxItems: 10,
      },
    ],
    videoSections: [
      {
        id: 'video-spotlight',
        title: 'Video Spotlight',
        subtitle: 'Hero video placement for the latest visual release.',
        contentTypes: ['video', 'live'],
        actionLabel: 'Watch',
        destinationTab: 'videos',
        maxItems: 6,
      },
      {
        id: 'worship-screen',
        title: 'Worship Screen',
        subtitle: 'Worship-focused videos and replays for the video tab.',
        contentTypes: ['video', 'playlist', 'live'],
        actionLabel: 'Watch',
        destinationTab: 'videos',
        maxItems: 8,
      },
      {
        id: 'message-replays',
        title: 'Message Replays',
        subtitle: 'Teaching and message content curated for easy viewing.',
        contentTypes: ['video', 'announcement'],
        actionLabel: 'Watch',
        destinationTab: 'videos',
        maxItems: 8,
      },
      {
        id: 'live-now',
        title: 'Live Now',
        subtitle: 'Current or recent live sessions available from the video screen.',
        contentTypes: ['live', 'video'],
        actionLabel: 'Open Live',
        destinationTab: 'live',
        maxItems: 8,
      },
    ],
    playerSections: [
      {
        id: 'music-queue',
        title: 'Keep Listening',
        subtitle: 'Songs, worship sets, and message audio ready for the music player.',
        contentTypes: ['audio', 'playlist'],
        actionLabel: 'Listen',
        destinationTab: 'player',
        maxItems: 10,
      },
      {
        id: 'worship-playlists',
        title: 'Worship Playlists',
        subtitle: 'Collections and longer listening journeys.',
        contentTypes: ['playlist', 'audio'],
        actionLabel: 'Browse',
        destinationTab: 'library',
        maxItems: 8,
      },
      {
        id: 'audio-messages',
        title: 'Message Audio',
        subtitle: 'Teaching and message recordings tailored for listening.',
        contentTypes: ['audio', 'announcement'],
        actionLabel: 'Open',
        destinationTab: 'player',
        maxItems: 8,
      },
    ],
    librarySections: [
      {
        id: 'most-played',
        title: 'Most Played',
        subtitle: 'Your strongest listening patterns and familiar replays.',
        contentTypes: ['audio', 'video', 'playlist', 'live'],
        actionLabel: 'Play',
        destinationTab: 'player',
        maxItems: 10,
      },
      {
        id: 'saved-music',
        title: 'Saved Music',
        subtitle: 'Music and message audio you have kept in your personal collection.',
        contentTypes: ['audio', 'playlist'],
        actionLabel: 'Music',
        destinationTab: 'player',
        maxItems: 10,
      },
      {
        id: 'playlist-collections',
        title: 'Playlists',
        subtitle: 'Collections and grouped listening journeys from your library.',
        contentTypes: ['playlist', 'audio'],
        actionLabel: 'Search',
        destinationTab: 'search',
        maxItems: 8,
      },
    ],
  },
  navigation: {
    tabs: [
      { id: 'home', label: 'Home', icon: 'home-filled' },
      { id: 'player', label: 'Music', icon: 'graphic-eq' },
      { id: 'videos', label: 'Videos', icon: 'smart-display' },
      { id: 'live', label: 'Live', icon: 'live-tv' },
      { id: 'library', label: 'Library', icon: 'library-music' },
    ],
  },
  discovery: {
    categories: ['All', 'audio', 'video', 'playlist', 'live', 'announcement'],
    shortcuts: [
      {
        id: 'worship',
        icon: 'graphic-eq',
        label: 'Trending worship',
        query: 'worship',
        category: 'audio',
      },
      {
        id: 'live',
        icon: 'live-tv',
        label: 'Live now',
        query: 'live',
        category: 'live',
      },
      {
        id: 'message',
        icon: 'menu-book',
        label: 'Message audio',
        query: 'message',
        category: 'announcement',
      },
    ],
  },
  settingsHub: {
    sections: [
      {
        id: 'account',
        title: 'Account',
        items: [
          {
            id: 'profile',
            icon: 'person-outline',
            label: 'Profile',
            hint: 'Name, email, and account details',
            destination: 'profile',
          },
          {
            id: 'library',
            icon: 'library-music',
            label: 'Your Library',
            hint: 'Saved listening and playlists',
            destination: 'tabs.library',
          },
          {
            id: 'privacy',
            icon: 'shield',
            label: 'Privacy',
            hint: 'Permissions and account controls',
            destination: 'settings.privacy',
          },
        ],
      },
      {
        id: 'discover',
        title: 'Discover',
        items: [
        {
          id: 'live',
          icon: 'live-tv',
          label: 'Live & Replays',
          hint: 'Current broadcasts, upcoming sessions, and recent replays',
          destination: 'tabs.live',
        },
        {
          id: 'videos',
          icon: 'ondemand-video',
          label: 'Video Hub',
          hint: 'Featured watchlists, live clips, and message replays',
          destination: 'tabs.videos',
        },
          {
            id: 'donate',
            icon: 'volunteer-activism',
            label: 'Support the Ministry',
            hint: 'Give and support the mission',
            destination: 'settings.donate',
          },
        ],
      },
      {
        id: 'support',
        title: 'Support',
        items: [
          {
            id: 'help',
            icon: 'help-outline',
            label: 'Help',
            hint: 'FAQs and support options',
            destination: 'settings.help',
          },
          {
            id: 'about',
            icon: 'info-outline',
            label: 'About ClaudyGod',
            hint: 'Learn about the ministry and the platform',
            destination: 'settings.about',
          },
          {
            id: 'rate',
            icon: 'rate-review',
            label: 'Rate App',
            hint: 'Share feedback about the experience',
            destination: 'settings.rate',
          },
        ],
      },
    ],
  },
};
