import { env } from '../../config/env';
import { pool } from '../../db/pool';
import { isMissingDatabaseStructureError } from '../../lib/postgres';
import type { JwtClaims } from '../../utils/jwt';

interface AdCopySuggestionInput {
  sponsorName: string;
  placement: 'landing' | 'home' | 'videos' | 'player' | 'live' | 'library' | 'search';
  objective: string;
  audience?: string;
  landingUrl?: string;
  tone?: string;
  notes?: string;
}

interface AdCopySuggestion {
  headline: string;
  body: string;
  ctaLabel: string;
  audienceTags: string[];
  rationale: string;
}

function normalizeTags(tags: string[]): string[] {
  return [...new Set(tags.map((item) => item.trim()).filter(Boolean))].slice(0, 8);
}

function buildHeuristicSuggestion(input: AdCopySuggestionInput): AdCopySuggestion {
  const sponsor = input.sponsorName.trim();
  const objective = input.objective.trim();
  const placement = input.placement === 'player' ? 'music' : input.placement;

  return {
    headline: `${sponsor} on ClaudyGod ${placement}`,
    body: `${objective}. Structured for a ${placement} placement with a clear, respectful call to action inside the ClaudyGod experience.`,
    ctaLabel: input.placement === 'landing' ? 'Learn more' : 'Open now',
    audienceTags: normalizeTags([
      input.placement,
      ...(input.audience ? input.audience.split(',') : []),
      ...(input.notes ? input.notes.split(/[,.]/) : []),
    ]),
    rationale: 'Generated by the built-in heuristic engine because no external AI provider is configured.',
  };
}

function extractJsonObject(text: string): AdCopySuggestion | null {
  const start = text.indexOf('{');
  const end = text.lastIndexOf('}');
  if (start === -1 || end === -1 || end <= start) return null;

  try {
    const parsed = JSON.parse(text.slice(start, end + 1));
    if (
      typeof parsed?.headline === 'string' &&
      typeof parsed?.body === 'string' &&
      typeof parsed?.ctaLabel === 'string' &&
      Array.isArray(parsed?.audienceTags) &&
      typeof parsed?.rationale === 'string'
    ) {
      return {
        headline: parsed.headline.trim(),
        body: parsed.body.trim(),
        ctaLabel: parsed.ctaLabel.trim(),
        audienceTags: normalizeTags(parsed.audienceTags.map(String)),
        rationale: parsed.rationale.trim(),
      };
    }
  } catch {}

  return null;
}

async function persistGenerationRun(params: {
  actor: JwtClaims;
  mode: 'heuristic' | 'remote';
  providerName: string;
  input: AdCopySuggestionInput;
  output: AdCopySuggestion;
}) {
  try {
    await pool.query(
      `INSERT INTO ai_generation_runs (feature_key, provider_name, mode, actor_user_id, input_payload, output_payload)
       VALUES ($1, $2, $3, $4, $5::jsonb, $6::jsonb)`,
      [
        'ad-copy',
        params.providerName,
        params.mode,
        params.actor.sub,
        JSON.stringify(params.input),
        JSON.stringify(params.output),
      ],
    );
  } catch (error) {
    if (isMissingDatabaseStructureError(error)) {
      return;
    }
    throw error;
  }
}

async function tryRemoteSuggestion(input: AdCopySuggestionInput): Promise<AdCopySuggestion | null> {
  if (!env.AI_PROVIDER_URL || !env.AI_PROVIDER_API_KEY || !env.AI_MODEL) {
    return null;
  }

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), env.AI_TIMEOUT_MS);

  try {
    const response = await fetch(`${env.AI_PROVIDER_URL.replace(/\/+$/, '')}/chat/completions`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${env.AI_PROVIDER_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: env.AI_MODEL,
        temperature: 0.7,
        messages: [
          {
            role: 'system',
            content:
              'You generate concise ad copy for a Christian streaming app. Return only JSON with keys headline, body, ctaLabel, audienceTags, rationale.',
          },
          {
            role: 'user',
            content: JSON.stringify(input),
          },
        ],
      }),
      signal: controller.signal,
    });

    if (!response.ok) {
      return null;
    }

    const payload = (await response.json()) as {
      choices?: { message?: { content?: string } }[];
    };
    const content = String(payload?.choices?.[0]?.message?.content || '');
    return extractJsonObject(content);
  } catch {
    return null;
  } finally {
    clearTimeout(timeout);
  }
}

export async function generateAdCopySuggestion(actor: JwtClaims, input: AdCopySuggestionInput): Promise<{
  suggestion: AdCopySuggestion;
  meta: { mode: 'heuristic' | 'remote'; provider: string };
}> {
  const remote = await tryRemoteSuggestion(input);
  const suggestion = remote ?? buildHeuristicSuggestion(input);
  const mode = remote ? 'remote' : 'heuristic';
  const provider = remote ? env.AI_PROVIDER_NAME : 'Built-in heuristic engine';

  await persistGenerationRun({
    actor,
    mode,
    providerName: provider,
    input,
    output: suggestion,
  });

  return {
    suggestion,
    meta: { mode, provider },
  };
}
