#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

CI_DATABASE_URL="${CI_DATABASE_URL:-postgresql://postgres:ci-password@db.your-project.supabase.co:5432/postgres}"
CI_SUPABASE_URL="${CI_SUPABASE_URL:-https://your-project.supabase.co}"
CI_SUPABASE_PUBLISHABLE_KEY="${CI_SUPABASE_PUBLISHABLE_KEY:-sb_publishable__ci_placeholder_key}"
CI_SUPABASE_SERVICE_ROLE_KEY="${CI_SUPABASE_SERVICE_ROLE_KEY:-ci-supabase-service-role-key}"
CI_YOUTUBE_API_KEY="${CI_YOUTUBE_API_KEY:-AIzaSyCIPlaceholderKeyValue1234567890ABCD}"
CI_YOUTUBE_CHANNEL_ID="${CI_YOUTUBE_CHANNEL_ID:-https://www.youtube.com/@YourChannel}"
CI_POSTFIX_SMTP_USERNAME="${CI_POSTFIX_SMTP_USERNAME:-ci-brevo-username}"
CI_POSTFIX_SMTP_PASSWORD="${CI_POSTFIX_SMTP_PASSWORD:-ci-brevo-password}"

cat > "$ROOT_DIR/.env.development" <<EOF
# Runtime
API_HOST=0.0.0.0
API_PORT=4000
WEB_PORT=5173

# Supabase PostgreSQL
DATABASE_URL=${CI_DATABASE_URL}
DATABASE_SSL=true
REDIS_URL=redis://redis:6379

# Security and auth
JWT_ACCESS_SECRET=ci-development-jwt-secret-with-at-least-thirty-two-characters
JWT_ACCESS_TTL=1d
BCRYPT_ROUNDS=12
MOBILE_API_KEY=ci-mobile-api-key-with-sufficient-length
AUTH_PUBLIC_BASE_URL=https://admin.dev.example.com
AUTH_VERIFY_EMAIL_PATH=/verify-email
AUTH_RESET_PASSWORD_PATH=/reset-password
AUTH_SIGN_IN_PATH=/sign-in
AUTH_ACCOUNT_REVIEW_PATH=/settings/account
AUTH_VERIFICATION_TOKEN_TTL_MINUTES=1440
AUTH_PASSWORD_RESET_TOKEN_TTL_MINUTES=30
AUTH_REQUIRE_EMAIL_VERIFICATION=false
CORS_ORIGIN=https://admin.dev.example.com,https://app.dev.example.com

# Admin web
VITE_API_URL=https://api.dev.example.com
VITE_GOOGLE_LOGIN_URL=
VITE_MOBILE_PREVIEW_URL=https://app.dev.example.com

# Mobile app
EXPO_PUBLIC_API_URL=
EXPO_PUBLIC_SUPABASE_URL=${CI_SUPABASE_URL}
EXPO_PUBLIC_SUPABASE_KEY=${CI_SUPABASE_PUBLISHABLE_KEY}
EAS_PROJECT_ID=00000000-0000-0000-0000-000000000000

# Supabase backend
SUPABASE_URL=${CI_SUPABASE_URL}
SUPABASE_SERVICE_ROLE_KEY=${CI_SUPABASE_SERVICE_ROLE_KEY}
SUPABASE_STORAGE_BUCKET=mobile-uploads

# Email
EMAIL_BRAND_NAME=ClaudyGod
EMAIL_SUPPORT_EMAIL=support@example.com
EMAIL_SUPPORT_URL=
MAIL_FROM="ClaudyGod <noreply@example.com>"
MAIL_REPLY_TO=support@example.com
ADMIN_ALERT_EMAILS=ops@example.com,admin@example.com
SMTP_PROVIDER=postfix
SMTP_HOST=postfix-relay
SMTP_PORT=25
SMTP_SECURE=false
SMTP_POOL=true
SMTP_MAX_CONNECTIONS=5
SMTP_MAX_MESSAGES=100
SMTP_CONNECTION_TIMEOUT_MS=30000
SMTP_GREETING_TIMEOUT_MS=30000
SMTP_REQUIRE_TLS=false
SMTP_TLS_REJECT_UNAUTHORIZED=true
POSTFIX_MYHOSTNAME=mail.dev.example.com
POSTFIX_RELAY_HOST=smtp-relay.brevo.com
POSTFIX_RELAY_PORT=587
POSTFIX_SMTP_USERNAME=${CI_POSTFIX_SMTP_USERNAME}
POSTFIX_SMTP_PASSWORD=${CI_POSTFIX_SMTP_PASSWORD}

# YouTube
YOUTUBE_API_KEY=${CI_YOUTUBE_API_KEY}
YOUTUBE_CHANNEL_ID=${CI_YOUTUBE_CHANNEL_ID}
YOUTUBE_MAX_RESULTS=12

# Seed admin
SEED_ADMIN_EMAIL=admin@example.com
SEED_ADMIN_PASSWORD=ChangeMe123!
SEED_ADMIN_DISPLAY_NAME=Claudy Admin
SEED_ADMIN_ON_BOOT=true
EOF

cat > "$ROOT_DIR/.env.production" <<EOF
# Runtime
API_HOST=0.0.0.0
API_PORT=4000
ADMIN_DOMAIN=admin.example.com
API_DOMAIN=api.example.com
APP_DOMAIN=app.example.com
TRAEFIK_PUBLIC_NETWORK=traefik-public
TRAEFIK_CERT_RESOLVER=letsencrypt

# Supabase PostgreSQL
DATABASE_URL=${CI_DATABASE_URL}
DATABASE_SSL=true
REDIS_URL=redis://redis:6379

# Security and auth
JWT_ACCESS_SECRET=ci-production-jwt-secret-with-at-least-thirty-two-characters
JWT_ACCESS_TTL=1d
BCRYPT_ROUNDS=12
MOBILE_API_KEY=ci-production-mobile-api-key-with-sufficient-length
AUTH_PUBLIC_BASE_URL=https://admin.example.com
AUTH_VERIFY_EMAIL_PATH=/verify-email
AUTH_RESET_PASSWORD_PATH=/reset-password
AUTH_SIGN_IN_PATH=/sign-in
AUTH_ACCOUNT_REVIEW_PATH=/settings/account
AUTH_VERIFICATION_TOKEN_TTL_MINUTES=1440
AUTH_PASSWORD_RESET_TOKEN_TTL_MINUTES=30
AUTH_REQUIRE_EMAIL_VERIFICATION=true
CORS_ORIGIN=https://admin.example.com,https://app.example.com

# Admin web
VITE_API_URL=https://api.example.com
VITE_GOOGLE_LOGIN_URL=https://api.example.com/v1/auth/google/start
VITE_MOBILE_PREVIEW_URL=https://app.example.com

# Mobile app
EXPO_PUBLIC_API_URL=https://api.example.com
EXPO_PUBLIC_SUPABASE_URL=${CI_SUPABASE_URL}
EXPO_PUBLIC_SUPABASE_KEY=${CI_SUPABASE_PUBLISHABLE_KEY}
EAS_PROJECT_ID=00000000-0000-0000-0000-000000000000

# Supabase backend
SUPABASE_URL=${CI_SUPABASE_URL}
SUPABASE_SERVICE_ROLE_KEY=${CI_SUPABASE_SERVICE_ROLE_KEY}
SUPABASE_STORAGE_BUCKET=mobile-uploads

# Email
EMAIL_BRAND_NAME=ClaudyGod
EMAIL_SUPPORT_EMAIL=support@example.com
EMAIL_SUPPORT_URL=
MAIL_FROM="ClaudyGod <noreply@example.com>"
MAIL_REPLY_TO=support@example.com
ADMIN_ALERT_EMAILS=ops@example.com,admin@example.com
SMTP_PROVIDER=postfix
SMTP_HOST=postfix-relay
SMTP_PORT=25
SMTP_SECURE=false
SMTP_POOL=true
SMTP_MAX_CONNECTIONS=5
SMTP_MAX_MESSAGES=200
SMTP_CONNECTION_TIMEOUT_MS=30000
SMTP_GREETING_TIMEOUT_MS=30000
SMTP_REQUIRE_TLS=false
SMTP_TLS_REJECT_UNAUTHORIZED=true
POSTFIX_MYHOSTNAME=mail.example.com
POSTFIX_RELAY_HOST=smtp-relay.brevo.com
POSTFIX_RELAY_PORT=587
POSTFIX_SMTP_USERNAME=${CI_POSTFIX_SMTP_USERNAME}
POSTFIX_SMTP_PASSWORD=${CI_POSTFIX_SMTP_PASSWORD}

# YouTube
YOUTUBE_API_KEY=${CI_YOUTUBE_API_KEY}
YOUTUBE_CHANNEL_ID=${CI_YOUTUBE_CHANNEL_ID}
YOUTUBE_MAX_RESULTS=12

# Seed admin
SEED_ADMIN_EMAIL=admin@example.com
SEED_ADMIN_PASSWORD=ChangeMe123!
SEED_ADMIN_DISPLAY_NAME=Claudy Admin
SEED_ADMIN_ON_BOOT=false
EOF

echo "CI environment files created at $ROOT_DIR/.env.development and $ROOT_DIR/.env.production"
