import React from 'react';
import { Feather } from '@expo/vector-icons';

type FeatherName = React.ComponentProps<typeof Feather>['name'];

const ICON_ALIASES: Record<string, FeatherName> = {
  home: 'home',
  'home-filled': 'home',
  headphones: 'headphones',
  'graphic-eq': 'activity',
  'play-circle-filled': 'play-circle',
  'play-circle-outline': 'play-circle',
  'play-arrow': 'play',
  'smart-display': 'video',
  'video-library': 'film',
  'library-music': 'disc',
  'music-note': 'music',
  'queue-music': 'list',
  playlist: 'list',
  album: 'disc',
  mic: 'mic',
  library: 'bookmark',
  tune: 'sliders',
  settings: 'settings',
  sliders: 'sliders',
  devices: 'monitor',
  sun: 'sun',
  moon: 'moon',
  search: 'search',
  'search-off': 'search',
  'live-tv': 'radio',
  event: 'calendar',
  people: 'users',
  'volunteer-activism': 'heart',
  'card-giftcard': 'gift',
  'help-outline': 'help-circle',
  'bug-report': 'tool',
  'high-quality': 'volume-2',
  'notifications-none': 'bell',
  'security': 'shield',
  'privacy-tip': 'shield',
  policy: 'file-text',
  gavel: 'clipboard',
  'info-outline': 'info',
  'star-outline': 'star',
  palette: 'droplet',
  'auto-stories': 'book-open',
  'menu-book': 'book-open',
  'auto-awesome': 'star',
  'wifi-off': 'wifi-off',
  'arrow-forward': 'arrow-right',
  'arrow-back': 'arrow-left',
  'open-in-new': 'external-link',
  share: 'share-2',
  'ios-share': 'share-2',
  shuffle: 'shuffle',
  repeat: 'repeat',
  'skip-next': 'skip-forward',
  'skip-previous': 'skip-back',
  'chevron-right': 'chevron-right',
  'chevron-left': 'chevron-left',
  close: 'x',
  add: 'plus',
  favorite: 'heart',
  'favorite-border': 'heart',
  notifications: 'bell',
  'notifications-active': 'bell',
  email: 'mail',
  explore: 'compass',
  person: 'user',
  account: 'user',
  history: 'clock',
  download: 'download',
  verified: 'check-circle',
  'verified-user': 'user-check',
  'support-agent': 'message-circle',
  'bar-chart': 'bar-chart-2',
  grid: 'grid',
  link: 'link',
  visibility: 'eye',
};

export type AppIconName = string;

export function AppIcon({
  name,
  size = 20,
  color,
}: {
  name: AppIconName;
  size?: number;
  color: string;
}) {
  return <Feather name={ICON_ALIASES[name] ?? 'circle'} size={size} color={color} />;
}
